### ISSUE TITLE
[Suggestion] Reduce player initialization complexity 

### ISSUE THREAD

**Issue by chalimac** [mmai/glicko2js#10]
In order to initialize a player they have to be entered in the //Make players section and then also in the var players = [ section. I have to manage a tournament with a huge number of participants and this doubles the work.

is there any way to initialize a player only with glicko.makePlayer? Maybe an optional mode to reduce complexity.

Many thanks for your work. I follow and use it since the beginning. In 2013 I reported a bug: https://github.com/mmai/glicko2js/issues/2

**Comment by KenanY** [comment]
@chalimac I don't really understand your first sentence. Isn't creating a player only as simply as this?: 

``` js
(new glicko2.Glicko2()).makePlayer();
```

What's the `var players = [` section?

**Comment by chalimac** [comment]
In the example file index.html. Without this it does not work:

**Comment by chalimac** [comment]
var players = [
                { name:'Ryan', glicko: Ryan },
                { name:'Mary', glicko: Mary },
                { name:'Bob', glicko: Bob },
                { name:'John', glicko: John },
                { name:'Gaspard', glicko: Gaspard },
                { name:'Hector', glicko: Hector }
            ];

**Comment by chalimac** [comment]
I understand the above code is necessary for the ratings to display in the browser. But is there any function that can list all the players ratings on Chrome's javascript console? Like getRating() but returning all the players at once.

**Comment by KenanY** [comment]
@chalimac `glicko.getPlayers()`?

**Comment by chalimac** [comment]
@KenanY 

It does not work. At least in the Chrome console. It doesn't display the names and the ratings show as negative numbers. Thanks for looking into it. I would welcome a way to list he current rating of all players.

**Comment by KenanY** [comment]
@chalimac `glicko.getPlayers()` returns raw `Player` objects. This module does _not_ keep track of player names for you. The negative ratings you are seeing are the players' ratings but in "Glicko-2 scale" (this is how [the paper](http://www.glicko.net/glicko/glicko2.pdf) describes it). You have to use `player.getRating()` in order to get the rating in the expected scale.

**Comment by chalimac** [comment]
Thanks! This is what I needed.

This is unrelated, but do you know why Chrome's console returns: 

Uncaught TypeError: glicko.makeRace is not a function

after opening the example file?

I have in a folder the files glicko2.js and index.html. Do I need any other?

**Comment by KenanY** [comment]
@chalimac Do you have the latest version of the repository? I can call `glicko.makeRace()` from the console just fine if I open `example/index.html` in Chrome (I am at commit https://github.com/mmai/glicko2js/commit/931aa87fd6e1c5f5e067ea2f3d8a9f624a4b5ec1).

**Comment by chalimac** [comment]
That was it. Many thanks! Sorry to bother you. I know this is not a javascript course.

**Comment by KenanY** [comment]
@chalimac Happy to help :)
