### ISSUE TITLE
explanation on your example

### ISSUE THREAD

**Issue by BladeSe7en** [mmai/glicko2js#15]
Can you explain this example more please. It looks like 1700, 1400, 1550 are the players original ratings and 0.06 is the volatility. But  what the values 300, 30, and 100 for and why are they different per player.
 ```Mary = glicko.makePlayer(1700, 300, 0.06);
 Bob = glicko.makePlayer(1400, 30, 0.06);
John = glicko.makePlayer(1550, 100, 0.06);

**Comment by mmai** [comment]
This is the "rating deviation" (confidence on the rating accuracy). It is one of the three components  needed by the Glicko2 algorithm to compute the evolution of the player, and it evolves as well as the other two components, so you need to keep track of it. 

For new players, you can just use the defaults.
