### ISSUE TITLE
Issues when reaching around 200 games

### ISSUE THREAD

**Issue by oaeide** [mmai/glicko2js#16]
Hi. I am currently using this package to calculate player rating after matches (5v5). This works splendid, except when a player is closing in on around 200 games played. It then swings wildly, to the point that it will overflow an int after 1-3 games. Any idea as to what might cause this?

**Comment by mmai** [comment]
Hi, could you provide a code example showing this behavior ? I could not reproduce the problem in my tests.

**Comment by oaeide** [comment]
`async function calculateMMRforGame(game_id, map) {

	date = new Date().getTime();
    console.time('MMRupdate_' + date);
    const recalc = false;

    await db.tx(async client => {
        //First we get the game that we are calculating for, making sure to check that it is a valid MMR game
        let game = await client.query(
            "select id, winner from games where id = $1 and cheat_mode = false and game_mode = 1 and mmr_calculated = $2 and game_time > 300 and map = $3 and start_time is not null limit 1", [game_id, recalc, map]
        );
        if (!game.rows[0]) {
            console.log(
                "No game that should be calculated MMR for was found with that ID"
            );
            return;
        }

        //Gather player data for the given game
        let players_res = await client.query(
            "select u.id as id, jsonb_path_query(u.mmr, '$.\"2019\".Season_1') as mmr, team " +
            "from game_results as gr " +
            "join users as u on gr.user_id = u.id " +
            "where game_id = $1", [game.rows[0].id]
        );

        var settings = {
            // tau : "Reasonable choices are between 0.3 and 1.2, though the system should
            //      be tested to decide which value results in greatest predictive accuracy."
            tau: 0.7,
            // rating : default rating
            rating: 3000,
            //rd : Default rating deviation
            //     small number = good confidence on the rating accuracy
            rd: 350,
            //vol : Default volatility (expected fluctation on the player rating)
            vol: 0.10
        };
        var ranking = new glicko2.Glicko2(settings);

        rankings_radiant = [];
        rankings_dire = [];

        for (let p of players_res.rows) {

            var r = ranking.makePlayer(Number(p.mmr[mp].mmr));
            r.id = p.id;

            if (p.mmr[mp].vol && p.mmr[mp].rd) {
                r.setVol(Number(p.mmr[mp].vol));
                r.setRd(Number(p.mmr[mp].rd));
            }

            if (p.team == 2) {
                rankings_radiant.push(r);
            }

            if (p.team == 3) {
                rankings_dire.push(r);
            }
        }

        let winner, loser;

        if (game.rows[0].winner == 2) {
            winner = rankings_radiant;
            loser = rankings_dire;
        }

        if (game.rows[0].winner == 3) {
            winner = rankings_dire;
            loser = rankings_radiant;
        }

        var race = ranking.makeRace([winner, loser]);
        ranking.updateRatings(race);

        //Now, we tie it all together and update each players mmr
        for (let w of winner) {
            let w_p_res = await client.query(
                "select mmr " + "from users " + "where id = $1", [w.id]
            );

            var updated = w_p_res.rows[0].mmr;

            updated["2019"].Season_1[mp].mmr = w.getRating();
            updated["2019"].Season_1[mp].calibration_games =
                Number(updated["2019"].Season_1[mp].calibration_games) + 1;
            updated["2019"].Season_1[mp].rd = w.getRd();
            updated["2019"].Season_1[mp].vol = w.getVol();

            console.log(
                "Winner mmr for user: ",
                w.id,
                "is ",
                updated["2019"].Season_1[mp]
            );

            let updated_mmr = await client.query(
                "update users set mmr = $1 where id = $2", [updated, w.id]
            );
        }

        for (let l of loser) {
            let l_p_res = await client.query(
                "select mmr " + "from users " + "where id = $1", [l.id]
            );

            var updated = l_p_res.rows[0].mmr;

            updated["2019"].Season_1[mp].mmr = l.getRating();
            updated["2019"].Season_1[mp].calibration_games =
                Number(updated["2019"].Season_1[mp].calibration_games) + 1;
            updated["2019"].Season_1[mp].rd = l.getRd();
            updated["2019"].Season_1[mp].vol = l.getVol();

            console.log(
                "Loser mmr for user: ",
                l.id,
                "is ",
                updated["2019"].Season_1[mp]
            );

            let updated_mmr = await client.query(
                "update users set mmr = $1 where id = $2", [updated, l.id]
            );
        }

        //Now we update the game to set that MMR has been calculated for it
        let updated_game = await client.query(
            "update games set mmr_calculated = true where id = $1", [game.rows[0].id]
        );
        console.timeEnd('MMRupdate_' + date)
        return;
    });
}`

**Comment by oaeide** [comment]
[mmr_player_log.txt](https://github.com/mmai/glicko2js/files/4051104/mmr_player_log.txt)

 Log of a player with this issue

**Comment by oaeide** [comment]
We run about 5000 games per month, and this occurs with about 2-3 players each week. I never saw it happening with a player with less than 150 games. Could it be related to the value of τ?

We calculate after every match

**Comment by mmai** [comment]
You shouldn't use Races in your case, it generates artificial draws between players of the same team. So instead of 
```javascript
    var race = ranking.makeRace([winner, loser]);
    ranking.updateRatings(race);
```
it should be:
```javascript
    let matches = [];
    for (let pwinner of winner){
      for (let plooser of looser) {
        matches.push([pwinner, plooser, 1]);
      }
    }
    ranking.updateRatings(matches);
```
But there is space for improvement. I think we can mitigate the fact that these are team matches rather than individual matches by building a virtual opponent with the average characteristics of the other team. The code would become something like this:

```javascript
    function averagePlayer(players){
      let count = players.length;
      let rating = players.reduce( (a, b) => a.getRating() + b.getRating(), 0) / count;
      let rd = players.reduce( (a, b) => a.getRd() + b.getRd(), 0) / count;
      let vol = players.reduce( (a, b) => a.getVol() + b.getVol(), 0) / count;
      return new ranking.makePlayer(rating, rd, vol);
    }

    let avgWinner = averagePlayer(winner);
    let avgLooser = averagePlayer(looser);
    let matches = [];
    for (let pwinner of winner){
      matches.push([pwinner, avgLooser, 1]);
    }
    for (let plooser of looser) {
      matches.push([plooser, avgWinner, 0]);
    }
    ranking.updateRatings(matches);

```

The last improvement would be to not calculate after every game but after a period of time.

**Comment by oaeide** [comment]
Hi. Thank you so much for the input. I will try to implement your suggested solution. Calculating after a period is not really ideal, but I think its worth it to get a correct result. Would ~5 matches be sufficient?

**Comment by mmai** [comment]
The algorithm author says that the optimal number is around 10-15 matches, but I guess 5 matches would not be bad.

I've fixed a mistake in the `averagePlayer` code of my previous comment
