### ISSUE TITLE
Add support for prediction?

### ISSUE THREAD

**Issue by MarianoMolina** [mmai/glicko2js#19]
Hi! 

Thanks for this! Haven't fully tested it yet, but seems to be working pretty well. 

I was wondering if you considered adding a function that calculates the estimated outcome of a match based on the data available. Basically you provide the pairing and it returns the expected outcome, which is similar to the E() function, but not quite. Found this in an r/chess thread that looks good: 
Let P2 = Expected outcome for player 2. Then:
P2 = 1 / (1 + e-A)
with
A = g(sqrt(r12+r22)) * (s2-s1))
and
g(x) = 1/sqrt(1+3x2/pi2)

Best, 
Mariano.

**Comment by LordVertice** [comment]
Could you elaborate on how it's different to the E() function? In Glicko-1 for example, Glickman explicity gave us a function for predicting game outcomes, which was literally just Glicko-1's E() function except instad of taking just the opponent's RD into account, the function uses sqrt(RD²+RDj²). Perhaps a similar modication to Glicko-2's E() function would suffice for this issue?

Also I'm not sure if this repo is still actively maintained, there's a recent change to Glicko-2 that hasn't been implemented here yet.

**Comment by mmai** [comment]
@LordVertice thanks for letting me know about the change in the algorithm, I updated the code accordingly.

**Comment by mmai** [comment]
Thanks @MarianoMolina & @LordVertice , I implemented your suggestion ( both of you describe the same calculation).
You can now get the probability of player1 to win against player2  with `glicko.predict(player1, player2)`  or `player1.predict(player2)`
