### ISSUE TITLE
Question about increased RD over time

### ISSUE THREAD

**Issue by jamestomasino** [mmai/glicko2js#23]
In reading about Glicko2 I read that the RD of a player should increase over time if they haven't played any matches. Is that accurate and if so, does this library have a mechanism to handle it? If we only track rating, RD, and volitility how would the system know if a match hasn't been played for a long time?

**Comment by mmai** [comment]
Hello @jamestomasino, sorry I completly forgot your question.
When you record a match, Glicko2 updates ranking for the for all the players. So if you  record numerous matches without a player, its RD will increase.

**Comment by k2xl** [comment]
Hi @mmai - So in a real application - we need to load all players and all matches into memory?

**Comment by mmai** [comment]
Hi @k2xl,  that's a good question! You can load only the data relative to a player (its oppenents and matches) to update its ranking. I updated the readme with a  step by step procedure : [how to deal with a big database of players](https://github.com/mmai/glicko2js#how-to-deal-with-a-big-database-of-players)
